# Generated by Django 5.2 on 2025-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
